### ISSUE TITLE
Roadmap v1.0.0

### ISSUE THREAD

**Issue by sreichl** [epigen/MrBiomics#35]

**Comment by sreichl** [comment]
- [ ] Test GitHub directive without global env and full run to check if sourcing issue emerges
  - [ ] If not, comment global env and doc that full Snakemake is required. Minimal requires to uncommon global env BUT leads to loss of GitHub directive function when used as module. 
  - [ ] If issues emerge, doc as well as an open issue in MrBiomics that links all three Snakemake issues and that version has to be documented by the user.

**Comment by sreichl** [comment]
List of affected modules:

- [ ] https://github.com/epigen/scrnaseq_processing_seurat
- [ ] https://github.com/epigen/dea_seurat
- [ ] https://github.com/epigen/mixscape_seurat
- [ ] https://github.com/epigen/dea_limma
- [ ] https://github.com/epigen/enrichment_analysis

**Comment by sreichl** [comment]
- Similar/related learning: if you use resources (i.e., files) that are defined in configs they should be inputs to the rule not params. -> https://github.com/epigen/MrBiomics/issues/40

**Comment by sreichl** [comment]
**at the end**
- [ ] upgrade to latest Snakemake version (adapt docs/README)
- [ ] upgrade to latest SLURM executor plugin
- [ ] rerun all recipes for test (& debug)

**Comment by sreichl** [comment]
- [ ]  fullfill MrBiomics Snakemake catalog requirements such that listed in catalog
- [ ]  connect to zenodo
- [ ]  first release with v0.1.0 → 11 modules and 3/5 recipes
- [ ]  linkedIn post about v0.1.0 with 11 modules and 3/5 recipes → main purpose: call for stars!
